In [1]:
import pandas as pd

In [2]:
pd.Series(['Suci','Sweety','Fatema','Taharema','Tonuka'],index=[2,3,4,5,6])

2        Suci
3      Sweety
4      Fatema
5    Taharema
6      Tonuka
dtype: object

In [4]:
pd.Series([10,20,30,40,50],index=['ten','twenty','thirty','forty','fifty'])

ten       10
twenty    20
thirty    30
forty     40
fifty     50
dtype: int64

In [5]:
import numpy as np

In [7]:
marks=np.array([100,200,300,400,500])
marks

array([100, 200, 300, 400, 500])

In [8]:
seriesArray=pd.Series(marks,index=['1 hundread','2 hundread','3 hundread','4 hundread','5 hundread'])

In [9]:
seriesArray

1 hundread    100
2 hundread    200
3 hundread    300
4 hundread    400
5 hundread    500
dtype: int32

In [10]:
#Seris from dictionary

In [11]:
teammate={
    'Suchi':'Deya',
    'Abin':'Shirin',
    'Marufa':'Hridita'
}
teammate

{'Suchi': 'Deya', 'Abin': 'Shirin', 'Marufa': 'Hridita'}

In [12]:
seriesDictionary=pd.Series(teammate)

In [13]:
seriesDictionary

Suchi        Deya
Abin       Shirin
Marufa    Hridita
dtype: object

In [14]:
np.arange(3,8,1)

array([3, 4, 5, 6, 7])

In [16]:
np.arange(8,2,-1)

array([8, 7, 6, 5, 4, 3])

In [17]:
#Create Seies using arange

In [20]:
data=pd.Series(np.arange(8,3,-1),index=['eight','seven','six','five','four'])
data

eight    8
seven    7
six      6
five     5
four     4
dtype: int32

In [21]:
data['six':'four']=500

In [22]:
data

eight      8
seven      7
six      500
five     500
four     500
dtype: int32

In [23]:
num1=pd.Series([1,2,3,4,5],index=['a','c','d','e','f'])

In [24]:
num1

a    1
c    2
d    3
e    4
f    5
dtype: int64

In [25]:
num2=pd.Series([2,3,4,5],index=['a','b','g','d'])

In [26]:
num1+num2

a    3.0
b    NaN
c    NaN
d    8.0
e    NaN
f    NaN
g    NaN
dtype: float64

In [27]:
num1.add(num2,fill_value=0)

a    3.0
b    3.0
c    2.0
d    8.0
e    4.0
f    5.0
g    4.0
dtype: float64

In [28]:
num1-num2

a   -1.0
b    NaN
c    NaN
d   -2.0
e    NaN
f    NaN
g    NaN
dtype: float64

In [29]:
num1.sub(num2,fill_value=0)

a   -1.0
b   -3.0
c    2.0
d   -2.0
e    4.0
f    5.0
g   -4.0
dtype: float64

In [30]:
num1*num2

a     2.0
b     NaN
c     NaN
d    15.0
e     NaN
f     NaN
g     NaN
dtype: float64

In [31]:
num1.mul(num2,fill_value=1)

a     2.0
b     3.0
c     2.0
d    15.0
e     4.0
f     5.0
g     4.0
dtype: float64

In [32]:
num1/num2

a    0.5
b    NaN
c    NaN
d    0.6
e    NaN
f    NaN
g    NaN
dtype: float64

In [33]:
num1.div(num2,fill_value=1)

a    0.500000
b    0.333333
c    2.000000
d    0.600000
e    4.000000
f    5.000000
g    0.250000
dtype: float64

In [34]:
num1.index

Index(['a', 'c', 'd', 'e', 'f'], dtype='object')

In [35]:
num1.values

array([1, 2, 3, 4, 5], dtype=int64)

# Starting Dataframe Assignment

In [36]:
StudentMarks= {
    'Name':['Suci','Suci','Suci','Srabanti','Srabanti','Srabanti', 'Ashravy','Ashravy','Ashravy','Mishti','Mishti','Mishti'],
 'UnitTest':[1,2,3,1,2,3,1,2,3,1,2,3],
 'DataMining':[22,21,14,20,23,22,23,24,12,15,18,17],
 'AI':[21,20,19,17,15,18,19,22,25,22,21,18],
 'Graphics':[18,17,15,22,21,19,20,24,19,25,25,20],
 'ImageProcessing':[20,22,24,24,25,23,15,17,21,22,24,25],
 'Cryptography':[21,24,23,19,15,13,22,21,23,22,23,20]
 }
 

In [37]:
import pandas as pd

In [38]:
data=pd.DataFrame(StudentMarks)

In [39]:
data

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
0       Suci         1          22  21        18               20   
1       Suci         2          21  20        17               22   
2       Suci         3          14  19        15               24   
3   Srabanti         1          20  17        22               24   
4   Srabanti         2          23  15        21               25   
5   Srabanti         3          22  18        19               23   
6    Ashravy         1          23  19        20               15   
7    Ashravy         2          24  22        24               17   
8    Ashravy         3          12  25        19               21   
9     Mishti         1          15  22        25               22   
10    Mishti         2          18  21        25               24   
11    Mishti         3          17  18        20               25   

    Cryptography  
0             21  
1             24  
2             23  
3             19  
4             15  
5             13  
6             22  
7             21  
8             23  
9             22  
10            23  
11            20

In [40]:
data[data.UnitTest>2]

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
2       Suci         3          14  19        15               24   
5   Srabanti         3          22  18        19               23   
8    Ashravy         3          12  25        19               21   
11    Mishti         3          17  18        20               25   

    Cryptography  
2             23  
5             13  
8             23  
11            20

In [41]:
data.max()

Name               Suci
UnitTest              3
DataMining           24
AI                   25
Graphics             25
ImageProcessing      25
Cryptography         24
dtype: object

In [42]:
data.max(numeric_only=True)

UnitTest            3
DataMining         24
AI                 25
Graphics           25
ImageProcessing    25
Cryptography       24
dtype: int64

In [43]:
data[data['UnitTest']==3]

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
2       Suci         3          14  19        15               24   
5   Srabanti         3          22  18        19               23   
8    Ashravy         3          12  25        19               21   
11    Mishti         3          17  18        20               25   

    Cryptography  
2             23  
5             13  
8             23  
11            20

In [44]:
unitTest3 = data[data['UnitTest']==3]

In [45]:
unitTest3

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
2       Suci         3          14  19        15               24   
5   Srabanti         3          22  18        19               23   
8    Ashravy         3          12  25        19               21   
11    Mishti         3          17  18        20               25   

    Cryptography  
2             23  
5             13  
8             23  
11            20

In [47]:
unitTest3['DataMining'].max()

22

In [48]:
marksSuci =data[data.Name == 'Suci']

In [49]:
marksSuci

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  Cryptography
0  Suci         1          22  21        18               20            21
1  Suci         2          21  20        17               22            24
2  Suci         3          14  19        15               24            23

In [50]:
data['DataMining'].sum()

231

In [51]:
data.shape

(12, 7)

In [52]:
data.count()

Name               12
UnitTest           12
DataMining         12
AI                 12
Graphics           12
ImageProcessing    12
Cryptography       12
dtype: int64

In [53]:
data.count(axis=1)

0     7
1     7
2     7
3     7
4     7
5     7
6     7
7     7
8     7
9     7
10    7
11    7
dtype: int64

In [54]:
data.mean(numeric_only=True)

UnitTest            2.000000
DataMining         19.250000
AI                 19.750000
Graphics           20.416667
ImageProcessing    21.833333
Cryptography       20.500000
dtype: float64

In [55]:
data

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
0       Suci         1          22  21        18               20   
1       Suci         2          21  20        17               22   
2       Suci         3          14  19        15               24   
3   Srabanti         1          20  17        22               24   
4   Srabanti         2          23  15        21               25   
5   Srabanti         3          22  18        19               23   
6    Ashravy         1          23  19        20               15   
7    Ashravy         2          24  22        24               17   
8    Ashravy         3          12  25        19               21   
9     Mishti         1          15  22        25               22   
10    Mishti         2          18  21        25               24   
11    Mishti         3          17  18        20               25   

    Cryptography  
0             21  
1             24  
2             23  
3             19  
4             15  
5             13  
6             22  
7             21  
8             23  
9             22  
10            23  
11            20

In [57]:
Suci=data[data['Name']=='Suci']
SuciMarks =Suci.loc[:,'DataMining':'Cryptography']

In [58]:
SuciMarks

DataMining  AI  Graphics  ImageProcessing  Cryptography
0          22  21        18               20            21
1          21  20        17               22            24
2          14  19        15               24            23

In [60]:
Suci=data[data['Name']=='Suci']
SuciMarks =Suci.iloc[:,2:]

In [61]:
SuciMarks

DataMining  AI  Graphics  ImageProcessing  Cryptography
0          22  21        18               20            21
1          21  20        17               22            24
2          14  19        15               24            23

In [62]:
data.median(numeric_only=True)

UnitTest            2.0
DataMining         20.5
AI                 19.5
Graphics           20.0
ImageProcessing    22.5
Cryptography       21.5
dtype: float64

In [64]:
data.quantile(numeric_only=True)

UnitTest            2.0
DataMining         20.5
AI                 19.5
Graphics           20.0
ImageProcessing    22.5
Cryptography       21.5
Name: 0.5, dtype: float64

In [66]:
data.quantile(numeric_only=True,q=.50)

UnitTest            2.0
DataMining         20.5
AI                 19.5
Graphics           20.0
ImageProcessing    22.5
Cryptography       21.5
Name: 0.5, dtype: float64

In [69]:
q1=data.quantile(numeric_only=True,q=0.25)
q1


UnitTest            1.00
DataMining         16.50
AI                 18.00
Graphics           18.75
ImageProcessing    20.75
Cryptography       19.75
Name: 0.25, dtype: float64

In [70]:
q3=data.quantile(numeric_only=True,q=0.75)
q3

UnitTest            3.00
DataMining         22.25
AI                 21.25
Graphics           22.50
ImageProcessing    24.00
Cryptography       23.00
Name: 0.75, dtype: float64

In [71]:
IQR = q3-q1

In [72]:
IQR

UnitTest           2.00
DataMining         5.75
AI                 3.25
Graphics           3.75
ImageProcessing    3.25
Cryptography       3.25
dtype: float64

In [74]:
Subjects=data.iloc[:,2:]

In [75]:
Subjects

DataMining  AI  Graphics  ImageProcessing  Cryptography
0           22  21        18               20            21
1           21  20        17               22            24
2           14  19        15               24            23
3           20  17        22               24            19
4           23  15        21               25            15
5           22  18        19               23            13
6           23  19        20               15            22
7           24  22        24               17            21
8           12  25        19               21            23
9           15  22        25               22            22
10          18  21        25               24            23
11          17  18        20               25            20

In [78]:
Subjects.quantile([0.25, 0.75])

DataMining     AI  Graphics  ImageProcessing  Cryptography
0.25       16.50  18.00     18.75            20.75         19.75
0.75       22.25  21.25     22.50            24.00         23.00

In [79]:
Subjects.var()

DataMining         15.840909
AI                  7.113636
Graphics            9.901515
ImageProcessing     9.969697
Cryptography       11.363636
dtype: float64

In [80]:
Subjects.std()

DataMining         3.980064
AI                 2.667140
Graphics           3.146667
ImageProcessing    3.157483
Cryptography       3.370999
dtype: float64

In [81]:
data.describe()

UnitTest  DataMining        AI   Graphics  ImageProcessing  \
count  12.000000   12.000000  12.00000  12.000000        12.000000   
mean    2.000000   19.250000  19.75000  20.416667        21.833333   
std     0.852803    3.980064   2.66714   3.146667         3.157483   
min     1.000000   12.000000  15.00000  15.000000        15.000000   
25%     1.000000   16.500000  18.00000  18.750000        20.750000   
50%     2.000000   20.500000  19.50000  20.000000        22.500000   
75%     3.000000   22.250000  21.25000  22.500000        24.000000   
max     3.000000   24.000000  25.00000  25.000000        25.000000   

       Cryptography  
count     12.000000  
mean      20.500000  
std        3.370999  
min       13.000000  
25%       19.750000  
50%       21.500000  
75%       23.000000  
max       24.000000

In [82]:
data.describe().T

count       mean       std   min    25%   50%    75%   max
UnitTest          12.0   2.000000  0.852803   1.0   1.00   2.0   3.00   3.0
DataMining        12.0  19.250000  3.980064  12.0  16.50  20.5  22.25  24.0
AI                12.0  19.750000  2.667140  15.0  18.00  19.5  21.25  25.0
Graphics          12.0  20.416667  3.146667  15.0  18.75  20.0  22.50  25.0
ImageProcessing   12.0  21.833333  3.157483  15.0  20.75  22.5  24.00  25.0
Cryptography      12.0  20.500000  3.370999  13.0  19.75  21.5  23.00  24.0

# Aggregate method

**The aggregate() method allows us to apply a function or list of functions names to be executed along one of the axis of dataframe ,default 0**

In [87]:
data.Graphics.aggregate(['min','max'],numeric_only=True)

min    15
max    25
Name: Graphics, dtype: int64

In [88]:
data[['DataMining','Graphics']].aggregate(['min','max'])

DataMining  Graphics
min          12        15
max          24        25

In [89]:
data.sort_values(by='DataMining')

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
8    Ashravy         3          12  25        19               21   
2       Suci         3          14  19        15               24   
9     Mishti         1          15  22        25               22   
11    Mishti         3          17  18        20               25   
10    Mishti         2          18  21        25               24   
3   Srabanti         1          20  17        22               24   
1       Suci         2          21  20        17               22   
0       Suci         1          22  21        18               20   
5   Srabanti         3          22  18        19               23   
4   Srabanti         2          23  15        21               25   
6    Ashravy         1          23  19        20               15   
7    Ashravy         2          24  22        24               17   

    Cryptography  
8             23  
2             23  
9             22  
11            20  
10            23  
3             19  
1             24  
0             21  
5             13  
4             15  
6             22  
7             21

In [90]:
data.sort_values(by='DataMining',ascending=False)

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
7    Ashravy         2          24  22        24               17   
4   Srabanti         2          23  15        21               25   
6    Ashravy         1          23  19        20               15   
0       Suci         1          22  21        18               20   
5   Srabanti         3          22  18        19               23   
1       Suci         2          21  20        17               22   
3   Srabanti         1          20  17        22               24   
10    Mishti         2          18  21        25               24   
11    Mishti         3          17  18        20               25   
9     Mishti         1          15  22        25               22   
2       Suci         3          14  19        15               24   
8    Ashravy         3          12  25        19               21   

    Cryptography  
7             21  
4             15  
6             22  
0             21  
5             13  
1             24  
3             19  
10            23  
11            20  
9             22  
2             23  
8             23

In [91]:
data.sort_values(by=['AI','ImageProcessing'])

Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  \
4   Srabanti         2          23  15        21               25   
3   Srabanti         1          20  17        22               24   
5   Srabanti         3          22  18        19               23   
11    Mishti         3          17  18        20               25   
6    Ashravy         1          23  19        20               15   
2       Suci         3          14  19        15               24   
1       Suci         2          21  20        17               22   
0       Suci         1          22  21        18               20   
10    Mishti         2          18  21        25               24   
7    Ashravy         2          24  22        24               17   
9     Mishti         1          15  22        25               22   
8    Ashravy         3          12  25        19               21   

    Cryptography  
4             15  
3             19  
5             13  
11            20  
6             22  
2             23  
1             24  
0             21  
10            23  
7             21  
9             22  
8             23

In [106]:
group=data.groupby(['Name'])
group

# Group By

In [107]:
group.first()

UnitTest  DataMining  AI  Graphics  ImageProcessing  Cryptography
Name                                                                       
Ashravy          1          23  19        20               15            22
Mishti           1          15  22        25               22            22
Srabanti         1          20  17        22               24            19
Suci             1          22  21        18               20            21

In [108]:
group.get_group('Suci')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1568\310802690.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  group.get_group('Suci')


Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  Cryptography
0  Suci         1          22  21        18               20            21
1  Suci         2          21  20        17               22            24
2  Suci         3          14  19        15               24            23

In [109]:
group.get_group('Suci')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1568\310802690.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  group.get_group('Suci')


Name  UnitTest  DataMining  AI  Graphics  ImageProcessing  Cryptography
0  Suci         1          22  21        18               20            21
1  Suci         2          21  20        17               22            24
2  Suci         3          14  19        15               24            23